// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnVc_w86_1wxn0Mjwa6lEEZ2PnT2PJjs',
    appId: '1:462517308515:web:f5d73e7bb66ae566273c56',
    messagingSenderId: '462517308515',
    projectId: 'campus-catalogue-c67bb',
    authDomain: 'campus-catalogue-c67bb.firebaseapp.com',
    storageBucket: 'campus-catalogue-c67bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdLY3X7Hu__8UKseadsnhqpqe-hG5Uoc',
    appId: '1:462517308515:android:b05854ebca6de05d273c56',
    messagingSenderId: '462517308515',
    projectId: 'campus-catalogue-c67bb',
    storageBucket: 'campus-catalogue-c67bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRzX0-s0xdVETu_filBiWI4CLErWP6oI0',
    appId: '1:462517308515:ios:8920252641f224b7273c56',
    messagingSenderId: '462517308515',
    projectId: 'campus-catalogue-c67bb',
    storageBucket: 'campus-catalogue-c67bb.appspot.com',
    iosBundleId: 'com.example.cc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRzX0-s0xdVETu_filBiWI4CLErWP6oI0',
    appId: '1:462517308515:ios:8920252641f224b7273c56',
    messagingSenderId: '462517308515',
    projectId: 'campus-catalogue-c67bb',
    storageBucket: 'campus-catalogue-c67bb.appspot.com',
    iosBundleId: 'com.example.cc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDnVc_w86_1wxn0Mjwa6lEEZ2PnT2PJjs',
    appId: '1:462517308515:web:2aa3ff64050930f2273c56',
    messagingSenderId: '462517308515',
    projectId: 'campus-catalogue-c67bb',
    authDomain: 'campus-catalogue-c67bb.firebaseapp.com',
    storageBucket: 'campus-catalogue-c67bb.appspot.com',
  );

}